CREATE DATABASE EMPLOYEE;

USE EMPLOYEE;


--CREATING TABLE---
CREATE TABLE EMPLOYEE
(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(10),
EMP_SAL INT,
EMP_DEPT VARCHAR(10),
EMP_AGE VARCHAR(20) );


---INSERT ROWS----
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_SAL, EMP_DEPT,EMP_AGE)
VALUES( 101, 'Keerthi', 35000, 'HR',35);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_SAL, EMP_DEPT,EMP_AGE)
VALUES( 102, 'Neeraja', NULL, 'Developer',35);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_SAL, EMP_DEPT,EMP_AGE)
VALUES( 103, 'Swetha', 55000, NULL ,35);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_SAL, EMP_DEPT,EMP_AGE)
VALUES( 104, 'Ameesa', 25000, 'Manager',35);

---VIEW THE DATA---
SELECT * FROM EMPLOYEE;

---UPDATE THE TABLE--
UPDATE EMPLOYEE  
SET EMP_SAL=45000
WHERE EMP_ID =102;

UPDATE EMPLOYEE
SET EMP_DEPT='Analyst'
WHERE EMP_DEPT IS NULL;

UPDATE EMPLOYEE
SET EMP_NAME='Mahesh'
WHERE EMP_ID=104;


UPDATE EMPLOYEE
SET EMP_AGE=27
WHERE EMP_ID=103;

UPDATE EMPLOYEE 
SET EMP_AGE=29
WHERE EMP_NAME='Mahesh';

--DELETE DATA
DELETE FROM EMPLOYEE
WHERE EMP_DEPT='Developer';

----FINAL DATA---
SELECT * FROM EMPLOYEE;




